### ISSUE TITLE
Deprecation warning and TypeError when resetting Anaconda 4.2.0 REPL in IPython interactive mode

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#2049]
Using the version of Anaconda that ships with VS 2017:

Start REPL with IPython interactive enabled
Execute a line of code
Click Reset.

```
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
Out[1]: 2
Resetting Python state.
C:\Program Files\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
C:\Program Files\Anaconda3\lib\site-packages\IPython\utils\traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\jupyter_client\channels.py", line 160, in run
    self.call_handlers(since_last_heartbeat)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\visualstudio_ipython_repl.py", line 95, in call_handlers
    msg_type = 'handle_' + msg['msg_type']
TypeError: 'float' object is not subscriptable

The interactive Python process has exited.
>>> 
```

**Comment by ryanyoung7259** [comment]
I am receiving the same error in Visual Studio 2015 as well.

**Comment by zooba** [comment]
I believe this is fixed, but since the file moved I can't easily check blame to see when it happened.

**Comment by lcorrigan** [comment]
Has always happened to me since VS2015.  Still happens with VS2017 + Python 2.7 + Anaconda 4.4

**Comment by huguesv** [comment]
It's fixed. It will be available in 15.6, whenever we start having preview builds for those.
