### ISSUE TITLE
Python Intellisense not working with Visual Studio 2017 15.2

### ISSUE THREAD

**Issue by nirmalraisoni** [Microsoft/PTVS#2613]
Hi I tried all possible options to enable Intellisense but not working

I am using Visual Studio Enterprise 2017 Version 15.2 (26430.6) IDE 

-Nirmal

**Comment by zooba** [comment]
Thanks for the report.

Would you be able to provide some more information about what you've tried? For example:
* have you created a Python project?
* have you looked in the Python Environments window to see whether the database needs refreshing?
* have you tried a Python Interactive Window to see if Intellisense works there?

**Comment by chintanp** [comment]
I would like to report the same problem. I am using VS Community 2017, 15.2 (26430.12), fresh install. I installed all the python environments during install 2.7, 3.6 (32, 64-bit). I also refreshed the db. Also, the intellisense works in the interactive window, just not in the text editor when I create a python project.

**Comment by zooba** [comment]
Can you show an example of what you are typing? There are some places where we can't provide Intellisense, but it's not obvious why not (well, it's obvious to me because I've debugged it often in the past :) ).

**Comment by chintanp** [comment]
When I type "print( .." in the text editor. I am not including (no statements) import anything yet. I saw this in one of the quickstart tutorials.

**Comment by shldngzh** [comment]
I would like to report the same issue. 

Everything worked perfectly until today afternoon. The Intellisense was working, I could send selected code to Interactive console by ctrl + Enter. 

However, now the Intellisense is not working, and the option "send to Interactive" is missing.

**Comment by zooba** [comment]
@shldngzh Did you do something this afternoon? Maybe install an update?

**Comment by shldngzh** [comment]
@zooba Thanks for your replying! I had a quick check and the only change I can recall/find is the most recent update (15.2 26430.13) was installed on last Friday/Monday. However, this morning, with nothing changed after work, everything is back to normal. Intellisense and send to Interactive are both working now. I'm confused but I'm thinking maybe some "hidden" problem is there.

**Comment by raoraozu** [comment]
I want to report the same issue that was posted before:

If I have a text editor with "import numpy as np" at the top, typing "np." gets exactly nothing, other than a red squiggle.
I cannot get any completions from a python class in the same file.
Meanwhile, the intellisense database for the Anaconda environment I'm using is up to date, and the package list looks accurate.
I get intellisense in the interactive window, but in the text editor immediately above, nothing.

![image](https://user-images.githubusercontent.com/15076451/27517722-99ce7284-5a03-11e7-8f78-0abae21b1797.png)

**Comment by zooba** [comment]
@shldngzh Glad it resolved itself. I would guess that one of the install caches had a problem, and it cleaned itself up automatically.

@raoraozu We have seen some issues where an editor window may not be associated with the correct environment. Can you try closing/reopening the file? (Also, so you're aware, the `import name as ...` and `from name import ...` cases are expected to show "<unknown type>" right now, and we are aware of limitations in pandas's factory functions. But the `np.` issue sounds unexpected.)

**Comment by ErfanEbrahimiBazaz** [comment]
I would like to report the same problem. I am using VS 2017, for python applications it is not working. For instance when I import cv2 or numpy as np, then when I put a dot after cv2. nothing comes, as in cv2.Laplacian(). When I hit ctrl+space, it doesn't help either.

**Comment by zooba** [comment]
Hi, @ErfanEbrahimiBazaz, thanks for the report! Can you check the following things:

1. Do you see any suggestions at all for anything else? Keywords?
2. Your project has the correct environment selected under "Python Environments"
3. That environment has the packages installed (right-click from Solution Explorer and select "Install Package" to jump to the packages list)
4. The database is up to date (you'll see a message on the completion popup if it is not)
5. Please try restarting Visual Studio and closing/opening the editor window (I recently fixed a bug around this area but it hasn't been released yet)

**Comment by ErfanEbrahimiBazaz** [comment]
Hi Steve,

thanks for your email. Regarding your questions:

1- The intellisense is giving me suggestions for the variables I have
defined. Like for example in my code I have the following line:
      data_path = os.path.join(PATH ,'data')

The intelliesense is suggestind data_path when I hit d, but when I type os
following by a dot, it doesn't show me anything, just <No Completions>
despite the fact I have imported os by (import os).

2- The environment I have chosen is new project -> Python Applicaton and I
write my code in the .py file provided.

3- When I right click on the solution explorer, there is no "Install
Package". Please kindly find the print screen of it in the attached files.

4- When I hit start, the only pop up window in python.exe window which
exectes the code. I have also provided a screen shot in the attached file.
Moreover, my dataset is has a file structure.

5- I have restarted mu system several times because I spent almost a month
on my project, but the intellisense has never worked for Python but is
working perfectly well as usual for C#.

More information, I have imported numpy, os, glob, Tensorflow, Keras and
their dependent libraries but the intellisense is showing nothing. However,
the projects runs perfectly well.

Thank you ince again for your attention and kind email Steve.
Waiting to hearing from you.

Best wishes
Erfan

**Comment by AddictivKaos** [comment]
Same issue. Also, the combo boxes for class and method selection at the top of the editor are empty

**Comment by athanhat** [comment]
Hi, I managed to reproduce a bug with **Intellisense** in Visual Studio 2017 15.2 and I also found a way to bypass this error. You may find my report and related issues in #2889 post

**Comment by zooba** [comment]
@ErfanEbrahimiBazaz It looks like you don't have any versions of Python installed, or at least any that have been detected by Visual Studio (we should normally show at least one item below "Python Environments", even if you haven't explicitly selected it yourself).

Could you open Tools, Python, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com?

**Comment by NaruNanao** [comment]
Hi, I would like to report the same issue. I installed Python 3.6 and Visual Studio Python extensions today and try to play with it. When I typed import <packageName> as <sth. short>, the Intellisense won't help and cannot detect anything inside the package (just like the 'import numpy as np' issue above). But if I type from <packageName> import ... , all the functions inside the package can be shown up. Plus, the Python Interactive window have the same problem.
I'm using Visual Studio Community 2017 Version 15.2(26430.16) and the installed Python Plugin is 3.0.17114.1

**Comment by zooba** [comment]
@NaruNanao `import sth as sth.short` is invalid syntax - you probably just want to type `import sth` here and then reference `sth.short` later.

**Comment by minaShaker** [comment]
it's not working for me either , i need to refresh the database every 10 secs (literally) so i would be able to use it !!

**Comment by zooba** [comment]
We just released 15.3 this week - please update to the latest version and try again. We fixed a number of IntelliSense issues, which hopefully includes the ones reported here.

**Comment by thogin** [comment]
@zooba 
Just updated to 15.3 and it's still not functioning properly.

I open a new python project and write `import re` on the first line. I get a few suggestions, but plain `re` isn't one of them.

Then when I continue on the next line with `re.`, I don't get any suggestions.

When I e.g. `import parser` however, I get this as a suggestion and also get suggestions when I later on type `parser.`.

**Comment by chartjunk** [comment]
Hi, I have the latest Visual Studio Community 2017 15.3.0 an Python workload 3.0.17208.1.

Using Python 3.6 64bit with the following imports
```python
import numpy as np
import pandas as pd
```
`pd.` gives suggestions in both Visual Studio's Code area and Python interactive. `.np` gives suggestions in Python interactive only.

**Comment by zooba** [comment]
@chartjunk Unfortunately, many of the issues around numpy aren't fixed yet (still working on them), but if you could attach the output of Tools, Python, Diagnostic Info then I may be able to give you some more specific advice. Your issue is probably not the same as any of the others in this thread.

**Comment by miklem** [comment]
Hi!
 I'm also have a problem with auto completion.
`f = open("C:\\test.txt")`
`text = f.readlines()`
`#text = "test"`
`f.close()`
`for line in text:`
    `line.`
There is no autocomplete for line after dot. But here it works:
`f = open("C:\\test.txt")`
`text = f.readlines()`
`text = "test"`
`f.close()`
`for line in text:`
    `line.`

Looks like readlines() not tell to VS properly about what type of data it returns. Same issue in VS code. But this code works in PyCharm.

**Comment by zooba** [comment]
@miklem Same deal as above - this is an ongoing limitation of the way we do static analysis. I believe PyCharm currently relies on manually entered information to get this right, while we do not do that (yet). There's no bug here.

**Comment by zooba** [comment]
Apologies to the OP, but since everyone keeps trying to hijack this thread for unrelated feature requests, I'm going to close and lock it.

If you encounter a bug that prevents *all* IntelliSense, or you see crashes or extremely high memory usage, please report it. Otherwise, we are working on long-term projects to improve the overall quality, and reporting individual issues does not help us.
