### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by MichaelGoulding** [Microsoft/PTVS#3120]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17262.1

System.InvalidOperationException: Failed to create entry for file
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<ConnectSubjectBufferAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by zooba** [comment]
I think I've already fixed this, but should probably double check. (If so, the fix hasn't been released yet, so thanks for reporting it)

**Comment by Arkoprabho** [comment]
Build: 3.0.17297.4, and this issue still persists. It is preventing me from opening a project specific ipython interactive window. More specifically this exception arises only when i use the shortcut Ctrl+K, Ctrl+` to open python environments and then further navigate to an ipython interactive window. On not using keyboard shortcuts, and instead using mouse to navigate and perform the same task, I did not run into this exception.
Also, this ends up crashing VS2017.

**Comment by huguesv** [comment]
This should be fixed now. We no longer raise InvalidOperationException from that code path.
