### ISSUE TITLE
An error pops up when run "Django Check, Django Migrate, Django Create Superuser...". 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6689]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/130715253-d3dd00d8-9d5c-43a1-b8ad-62973927d273.png)

**Steps to Reproduce**
1. Create a Django  Web Project
2. In solution explorer, right click on project and
- Python, make migrations >= 1.7
- Python, migrate >= 1.7
- Python, Django Create Superuser >= 1.7		
- Python, collect static files 
- Python, Django check >= 1.7

**Additional context and screenshots**
An error message pops up.
![image](https://user-images.githubusercontent.com/59192491/129515372-1e68d7b4-959f-4f89-b4a1-16e588c2e3db.png)

**Comment by rchiodo** [comment]
This should be fixed in newer builds.

**Comment by linette-zyy** [comment]
@rchiodo
This issue still reproduced on today's build.
![image](https://user-images.githubusercontent.com/59192491/132274712-e2c8bf45-09ff-4a57-813c-fa75fec2d68f.png)
