### ISSUE TITLE
Visual Studio considering python 3.10  as 0.0 and giving warning of support being dropped for 0.0 when it shouldn't (2022 preview)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6795]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-considering-python-310--a/1574894)._

---
[severity:It bothers me. A fix would be nice]
! [image.png] (https://aka.ms/dc/image?name=B0a0125ba564a4f419e9faa345546259d637720302395575702_20211109-102039-image.png&tid=0a0125ba564a4f419e9faa345546259d637720302395575702)

There is not much to explain, the above is probably enough to explain the issue.

---
#### Feedback Bot on 11/8/2021, 11:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment]
We need to investigate if 3.10 is broken in debugging. 3.10 is not officially supported by PTVS at this time. We should add 3.10 to our CTI test matrix.

**Comment by pauljurczak** [comment]
> 3.10 is not officially supported by PTVS at this time.

PTVS page (https://docs.microsoft.com/en-us/visualstudio/python/overview-of-python-tools-for-visual-studio) gives completely different impression:

![ptvs](https://user-images.githubusercontent.com/4933032/146431976-74851a17-af9a-426a-ad6e-835c6fe282ca.png)

**Comment by baylf2000** [comment]
@AdamYoblick Why did you close this issue? Is has not been resolved in any way. There is no information anywhere that specifies that a version of Python must be "supported", and even if that is true, then VS should not allow the use of an unsupported version, or at least warn users of the issue. What is happening is an obvious bug. It happened when Python 3.9 was delivered a year ago also, and the "fix" was obviously not effective.

Please open this issue again and mark it for the attention it so obviously requires.

**Comment by Artfunkel** [comment]
This bug prevents PTVS from recognising embedded Python 3.10 interpreters (e.g. within Blender 3.1). You can't debug Python code in these processes at all.

Please fix this soon!

**Comment by AdamYoblick** [comment]
Will do, this is my next bug to fix :)

**Comment by Tayinator** [comment]
How do we fix this in the meantime?

**Comment by AdamYoblick** [comment]
There is no fix in the meantime. Supporting a new version of python is not trivial, as our classes that wrap python c structs need to be updated to match.

In any case, this has been fixed and will be in the next preview version of VS.

**Comment by torzechowski1** [comment]
Maybe we need to get support for Python 0.0 the anarchy version of Python.

**Comment by oiChef** [comment]
MS should have released VS2022 with 3.9 not 3.10
This is still a problem in April.

**Comment by AdamYoblick** [comment]
@oiChef I'm not sure what you mean. VS2022 DID release with 3.9 support, and WITHOUT support for 3.10. That's precisely what this bug is reporting, and that's what was fixed.

**Comment by oiChef** [comment]
Odd. I just 2 days ago installed 2022 on a system, it was preconfigured with 3.10.
I manually installed 3.9.
Do you need more details about exactly what I installed? I pulled it right from MS. I see today there was an update a day after (12th). I downloaded on the 11th. 
![vs22](https://user-images.githubusercontent.com/103445186/163257148-a4855579-d475-4166-9c23-34f120aca4e2.png)

**Comment by AdamYoblick** [comment]
I'm not sure what you mean when you say "preconfigured with 3.10". There is no version of Visual Studio that has Python 3.10 bundled in it.

When you select "Python development" from the Visual Studio installer, you can optionally choose to install the Python interpreter, which we bundle into VS as a convenience. The checkout is unchecked by default, because we would rather you install it from python.org. See below:

![image](https://user-images.githubusercontent.com/29436557/163258038-6327e614-3369-4605-87be-822a854c6691.png)

You'll know if Visual Studio installed your version of python, because it will be under a shared VS directory, not in the normal python.org install location. It sounds like maybe your machine had python 3.10 installed on it before the VS install?

**Comment by oiChef** [comment]
You are correct. The system has an earlier installation of 3.10 in WindowsApps folder.
I did choose Python Development workload from the VS installer.
I later installed the 3.9 as I had missed the installation details selection. 3.9 is in the Shared folder.
Sorry for the goose chase. First time trying python in VS. Upgraded from VS2015.
Thank you for clearing this up.

**Comment by baylf2000** [comment]
> 


@AdamYoblick 
> @oiChef I'm not sure what you mean. VS2022 DID release with 3.9 support, and WITHOUT support for 3.10. That's precisely what this bug is reporting, and that's what was fixed.

Has it been fixed? I have the very latest version of VS2022 and I get the same error I have always had when trying to use Python 3.10

![image](https://user-images.githubusercontent.com/1748322/163309891-62b126be-9afb-496f-8222-d30ffbde5bd4.png)

**Comment by torzechowski1** [comment]
> > 
> 
> @AdamYoblick
> 
> > @oiChef I'm not sure what you mean. VS2022 DID release with 3.9 support, and WITHOUT support for 3.10. That's precisely what this bug is reporting, and that's what was fixed.
> 
> Has it been fixed? I have the very latest version of VS2022 and I get the same error I have always had when trying to use Python 3.10
> 
> ![image](https://user-images.githubusercontent.com/1748322/163309891-62b126be-9afb-496f-8222-d30ffbde5bd4.png)

I am writing code using 3.10.  to me this is just an annoying message.  We can write code all day long.

**Comment by baylf2000** [comment]
> 

@torzechowski1 

> I am writing code using 3.10. to me this is just an annoying message. We can write code all day long.

Perhaps you should read the issues above. It certainly has multiple impacts on people, despite your own personal indifference.

**Comment by oiChef** [comment]
> > 
> 
> @torzechowski1
> 
> > I am writing code using 3.10. to me this is just an annoying message. We can write code all day long.
> 
> Perhaps you should read the issues above. It certainly has multiple impacts on people, despite your own personal indifference.

I retracted mine. Newbie of python inside recent-VS.

**Comment by AdamYoblick** [comment]
@baylf2000 Yes, the issue has been fixed in an internal preview version, but that fix might not have made it out to the public yet.

**Comment by MichelBeaudet** [comment]
Hi,
Very annoying.  Where can we get the fix ?

**Comment by AdamYoblick** [comment]
@MichelBeaudet You should be able to download the latest preview version of VS2022 and it will contain the fix. Alternatively, you can wait for 17.2 GA (on 5/10) and that will also contain the fix.

**Comment by MichelBeaudet** [comment]
> @MichelBeaudet You should be able to download the latest preview version of VS2022 and it will contain the fix. Alternatively, you can wait for 17.2 GA (on 5/10) and that will also contain the fix.

Hi,
Thanks for the answer.

I already have VS2022 version 17.1.5 and still have the error!  So I understand that there's another version between 17.1.5 and 17.2.

**Comment by HolidayTheBoi** [comment]
>Hi,
Thanks for the answer.

I already have VS2022 version 17.1.5 and still have the error! So I understand that there's another version between 17.1.5 and 17.2.

Just enable preview updates in the installer
