### ISSUE TITLE
Embedded Python 3.10 interpreters not detected by debugger

### ISSUE THREAD

**Issue by Artfunkel** [microsoft/PTVS#6930]
**Describe the bug**
The embedded Python 3.10.2 interpreter within Blender 3.1 is not recognised by PTVS. You can attach to the process, but not debug any Python scripts running within it. Neither Python nor Python+Native debugging work.

**Steps to Reproduce**
1. [Download Blender 3.1](https://download.blender.org/release/Blender3.1/)
2. Start Blender and wait for it to finish loading
3. Try to attach to blender.exe from Visual Studio

**Expected behavior**
Python is displayed in the "Type" column of the Attach to Process window, and Python breakpoints are hit in script files.

**Additional context and screenshots**
Python scripts within earlier versions of Blender can still be debugged. This bug persists even if I delete the python310.dll file that Blender ships with and let it fall back on my system installation.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: VisualStudio.17.Preview/17.2.0-pre.2.0+32314.265
PTVS version: 17.0.22059.4
Python version: 3.10.2
Debugger Type (if applicable): No idea, can't see anything about this in the settings

**Comment by Artfunkel** [comment]
This is possibly related to #6900

**Comment by int19h** [comment]
When it's just Python, then the root cause is that Attach to Process in Python-only mode uses legacy ptvsd 3.x in current releases, which doesn't support new Python versions. https://github.com/microsoft/PTVS/pull/6916 should fix that; in the meantime, the workaround is to use TCP attach (`debugpy.listen()` etc), although debug server lifetime can be tricky to manage in some hosting scenarios.

**Comment by Artfunkel** [comment]
Thanks, that does indeed work.

Do you know when these changes will make their way into a 2022 preview? I just updated to 17.2 preview 2.1 but still can't attach directly.

**Comment by int19h** [comment]
It should come in the next preview.

**Comment by Artfunkel** [comment]
I have installed the next preview (Version 17.2.0 Preview 3.0) and this bug is not fixed. I still cannot attach to embedded Python 3.10 interpreters. Apparently I can't reopen issues so I hope you notice this comment.

![image](https://user-images.githubusercontent.com/3618066/163262545-0fe24553-0a61-45e1-ad3c-b5b77e5ae485.png)

Repro steps: launch Blender 3.1+ and try to attach to it.
