### ISSUE TITLE
reportMissingModuleSource:  Visual Studio 2022 / Python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7393]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022--Python/10264811)._

---
Hi,

I have a problem with Visual Studio 2022 / Python. I am using Visual Studio to write and debug Python code. 

I am not sure if this is a Visual Studio problem or a Python problem or both.

Note that this problem affects both edit mode in Visual Studio and run mode in Visual Studio. In other words, the same errors show up when a Python program is running (using F5 in Visual Studio).

The problem has an easy description, but is rather serious.

I use ‘from HDLmXXX import *’ statements, at the start of some of my Python programs (see 20230130_095849.jpg). That is pretty standard.  
[20230130_095849.jpg](https://aka.ms/dc/file?name=B46c16ad4df0c4ac781b6c4a776ed9827638106919756405258_20230130_095849.jpg&tid=46c16ad4df0c4ac781b6c4a776ed9827638106919756405258)

[20230130_095914.jpg](https://aka.ms/dc/file?name=B79775460b7f54f15955a77c082ade167638106919871443386_20230130_095914.jpg&tid=79775460b7f54f15955a77c082ade167638106919871443386)
 
However, the import classes (some of them) are unknown later. See 20230130_095914.jpg.  

Why do I get this error? What can I do about this?

---
#### Feedback Bot on 1/30/2023, 06:14 PM: 

(private comment, text removed)
#### pschaeffer on 2/2/2023, 05:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment]
Seems like a duplicate of #7068 and #6713

**Comment by StellaHuang95** [comment]
More from the original post:

I worked on this a bit further. It turns out to be a circular import problem (see below). The possible bug is that I never got an importError or any other exception. Instead, I got a runtime exception (NameError: name ‘IDLmAJAX’ is not defined). This problem can be easily (not really) reproduced be creating 3 (yes 3) files.
IDLmBuild.py

from IDLmAJAX import *
from IDLmUtility import *
IDLmUtility.getPerceptualHash(‘a’)

IDLmUtility.py

from IDLmAJAX import *
class IDLmUtility(object):
@staticmethod
def getPerceptualHash(urlStr):
print(IDLmAJAX)
IDLmAJAX.py

from IDLmUtility import *
class IDLmAJAX(object):
def runAJAX():
pass

Note that IDLmBuild.py is the ‘main’ program where execution should start. See below.

C:\Users\Peter\Documents\Visual Studio 2022\projects\PythonApps\PythonApps>py IDLmBuild.py
Traceback (most recent call last):
File “C:\Users\Peter\Documents\Visual Studio 2022\projects\PythonApps\PythonApps\IDLmBuild.py”, line 3, in <module>
IDLmUtility.getPerceptualHash(‘a’)
File “C:\Users\Peter\Documents\Visual Studio 2022\projects\PythonApps\PythonApps\IDLmUtility.py”, line 5, in getPercep
print(IDLmAJAX)
NameError: name ‘IDLmAJAX’ is not defined

**Comment by StellaHuang95** [comment]
Hi there, could you change `from IDLmAJAX import *` to `import IDLmAJAX`? That should solve your issue. I believe the former one only creates references to all things defined in module IDLmAJAX, but the module itself is not defined, so it won't work. Please re-open the ticket if the issue persists. Thanks.

**Comment by pschaeffer** [comment]
Hi StellaHuang95,

I made the changes you suggested (and some more) and the problem still exists. The current files are provided below.

IDLmAJAX.py

import IDLmUtility
class IDLmAJAX(object):
  def runAJAX():
    pass

IDLmBuild.py

import IDLmAJAX   
import IDLmUtility
IDLmUtility.g()

IDLmUtility.py

import IDLmAJAX
class IDLmUtility(object):  
  @staticmethod 
  def g(): 
    print(IDLmAJAX)

When I run IDLmBuild I get "module 'IDLmUtility' has no attribute 'g'"

Of course, that is not true. Worse, Python never detects/reports the circular imports.

Thank you

Peter Schaeffer

**Comment by pschaeffer** [comment]
Hi,

I tried the suggested change. It made no difference. I did not know how to reload the project, so I shutdown VS 2022 completely and restarted it (first I switched to strict mode).

Thank you

Peter Schaeffer

**Comment by pschaeffer** [comment]
Hi,

 

I tried the suggested change. It made no difference. I did not know how to reload the project, so I shutdown VS 2022 completely and restarted it (first I switched to strict mode).

 

Thank you

 

Peter Schaeffer

**Comment by StellaHuang95** [comment]
Great, glad that the issue has been resolved. And yes, reloading just means restart VS or close the project and open again.

**Comment by pschaeffer** [comment]
Hi,

I tried you suggested change. It did not resolve the problem. Indeed, it made no difference that I could tell.

Thank you

Peter Schaeffer

**Comment by StellaHuang95** [comment]
@pschaeffer Could you share the screenshot? So you're saying that after you changed to strict mode, the circular import error didn't show in the error list? Thanks!

**Comment by pschaeffer** [comment]
Hi Stella,

 

I carefully looked in the error list and found

 


Severity

Code

Description

Project

File

Line

Suppression State


Error (active)

 

Cycle detected in import chain  c:\Users\Peter\Documents\Visual Studio 2022\Projects\PythonApps\PythonApps\IDLmAJAX.py  c:\Users\Peter\Documents\Visual Studio 2022\Projects\PythonApps\PythonApps\IDLmUtility.py

 

C:\Users\Peter\Documents\Visual Studio 2022\Projects\PythonApps\PythonApps\IDLmAJAX.py

1

 

 

What is strange is that sometimes I see the ‘Cycle detected’ error message and sometimes I don’t.

 

Right now, I don’t have the error message.

 

Thank you

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
Hi,

Let me offer another comment. I would think Python would report a circular import error in all cases (at runtime). However, this does not appear to be true.

**Comment by StellaHuang95** [comment]
I wasn't able to repro this on my end, but I suspect that it may be related to the time it takes for Pylance to start the service instance and finish the diagnosis. In some cases, if the service instance isn't fully started, it may not be able to detect the cycle and the error won't appear . Could you be more specific on when you didn't see the ‘Cycle detected’ error message? Was this after loading the solution?

**Comment by pschaeffer** [comment]
I ran another test just a few minutes ago. Definitely still a problem. Should I send you the 'IDLM*' files so that you can reproduce the problem? My test environment is Visual Studio 2022 (PTVS). I also reproduced the same exact problem from the command line entirely outside of VS 2022. I can provide screen shots if that will help.

**Comment by StellaHuang95** [comment]
Thanks, I would be happy to take a look at the files and screenshots you have, but based on what you've described, it sounds like the issue may not be related to PTVS or Visual Studio. Since you mentioned that you were able to reproduce the problem outside of VS as well, it may be outside of our scope to fix. Nonetheless, I'd be glad to take a look and see if I can offer any suggestions or guidance. Please feel free to send over the files and screenshots.

**Comment by pschaeffer** [comment]
Hi,

 

Here are the files and screen shots I promised.

 

Thank you

 

Peter Schaeffer

**Comment by StellaHuang95** [comment]
I don't see the files. Could you try again and comment under this issue directly?

**Comment by pschaeffer** [comment]
Hello,

Here are the files. I put gif at the end of the py files because this system does not like py files. You will have to rename 3 files. All of the files to be renamed start with IDLM.

Thank you

Peter Schaeffer
![Python Error Inside VS2022](https://user-images.githubusercontent.com/3717450/233755386-72d83c86-69a6-4158-96e7-9fce870e762b.png)
![Python Error Outside of VS2022](https://user-images.githubusercontent.com/3717450/233755399-8c7eb18d-d5e9-48b7-801c-71f85ac71929.png)
![IDLmAJAX](https://user-images.githubusercontent.com/3717450/233755496-2bb7efb4-6ba0-4c84-b129-2e880f732132.gif)
![IDLmBuild](https://user-images.githubusercontent.com/3717450/233755505-244093dc-9a9a-424b-9f4c-ebcecd0a3cd1.gif)
![IDLmUtility](https://user-images.githubusercontent.com/3717450/233755509-c78ad72e-552d-4f58-8aea-f4d95b0b8722.gif)

**Comment by StellaHuang95** [comment]
Could you try zip it up and send the .zip file?

**Comment by pschaeffer** [comment]
Hi Stella,

 

How about this zipx file? 

 

Thank you

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
Hello Stella,

The actual file is a zipx file. However, I renamed it to be a jpeg file to get around upload restrictions.

Thank you

Peter Schaeffer
![Python Problems](https://user-images.githubusercontent.com/3717450/234477653-2622ecf5-3f3b-4e2c-b235-bde2698bf96f.jpeg)

**Comment by StellaHuang95** [comment]
I still couldn't access the files, were you able to upload .zip files? The supported file type seems include .zip. ![image](https://user-images.githubusercontent.com/100439259/234683773-27954efb-8f9b-4fad-bcf6-07a2cf59f480.png)

**Comment by pschaeffer** [comment]
Hello Stella,

Try again.

Thank you

Peter Schaeffer

[Problems.zip](https://github.com/microsoft/PTVS/files/11336889/Problems.zip)

**Comment by StellaHuang95** [comment]
Thanks, now I see the code. The issue is that you are trying to call the `g()` method directly from the module using `IDLmUtility.g()`, but `g()` is a static method in the `IDLmUtility` class. You can either change that to `IDLmUtility.IDLmUtility.g()` or change the import statement to `from IDLmUtility import IDLmUtility` to fix the error.

**Comment by pschaeffer** [comment]
Hello,

 

Thank you for the update. Shouldn’t I get some kind of import error with this structure?

 

Thank you

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
Hello,

Thank you for the update. Shouldn’t I get some kind of import error with this structure?

Thank you

Peter Schaeffer

**Comment by StellaHuang95** [comment]
Hi there, we wish we were able to thoroughly investigate all issues and leave all feature requests open indefinitely, but unfortunately, we have limited resources and it’s hard to organize and prioritize our work if we have a large number of issues open in our repository. If you find that this issue persists and falls within the scope of PTVS, could you please reopen it with the following details:

1. Detailed reproduction steps with expected and actual behavior.

2. Any sample code if different from the one provided.

3. Go to Tools -> Python -> Analysis, set your Log Level to Trace, and share the logs.

Thank you for your understanding!
