### ISSUE TITLE
ERROR: The process "xxxxx" not found

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7756]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/f50b90fc-1d53-49e8-a9b3-a330c06420b8)

**Steps to Reproduce**
1.New a python project
2.Check the Output window

**Expected behavior**
No errors pop up

**Actual behavior**
There are some errors pop up
```
ERROR: The process "10924" not found.
ERROR: The process with PID 5180 (child process of PID 8076) could not be terminated.
Reason: There is no running instance of the task.

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

ERROR: The process "3972" not found.
```
![errors](https://github.com/microsoft/PTVS/assets/59192491/e47197aa-4981-4024-bd92-228ba99b2ac4)

**Comment by StellaHuang95** [comment]
Can you try the following things:

- Make sure Python is installed on your machine.
- Make sure that the correct Python interpreter is selected for your project.
- Check for Running Processes: The error mentions processes with PIDs (Process IDs). You can open the Task Manager (Ctrl + Shift + Esc) and manually check if the mentioned PIDs are running. If not, try terminating any related processes and restart Visual Studio.

**Comment by linette-zyy** [comment]
@StellaHuang95 
The Python installed from workload and Python interpreter is selected for my project. And check the mentioned PIDs, not found the processes. 
![image](https://github.com/microsoft/PTVS/assets/59192491/d95855a3-1a36-4a84-86fc-428c86025ef6)
I tried terminating any related processes and restart Visual Studio, the error still displayed.

**Comment by StellaHuang95** [comment]
@linette-zyy Thanks. Can you try the following?
1. Check if your python 3.9 is added to `PATH`? 
2. Go to -> "start" and type "Manage App Execution Aliases". Go to it and turn off "Python".

**Comment by ttSpace** [comment]
I cannot repro it after adding python 3.9 to ```PATH```. And cannot find python in ```App Execution Aliases```.

![image](https://github.com/microsoft/PTVS/assets/82852072/6116b1ad-d7d1-4247-8c62-73ba4577c35e)

**Comment by ttSpace** [comment]
In today's build ```17.9.0 Preview 2.0 [34320.133.main]```, Python Package: ```17.0.23314.1```, I can repro it. (Python installed from Microsoft store)

![image](https://github.com/microsoft/PTVS/assets/82852072/73adda5a-a87c-4f9a-808a-202e36f7c4b5)

**Comment by StellaHuang95** [comment]
This should be fixed once PTVS consumes the latest pylance stable version.

**Comment by linette-zyy** [comment]
@StellaHuang95 This issue still repro on the latest build.
![image](https://github.com/microsoft/PTVS/assets/59192491/47cf3783-b7e4-4237-875e-9c52a3a232ba)
The pylance version:
![image](https://github.com/microsoft/PTVS/assets/59192491/8221bd99-1d7d-4d53-bd4a-debc57aa0da1)

![image](https://github.com/microsoft/PTVS/assets/59192491/c8dee7bd-3060-439f-bf64-fb276c964976)
Which stable version with pylance will fix this issue.

**Comment by StellaHuang95** [comment]
We haven't shipped the stable pylance version yet.
